openapi: 3.2.0
info:
  title: FarmCommand Recengine API
  termsOfService: https://www.farmcommand.com/terms-of-service
  contact:
    name: Product Support
    email: productsupport@farmersedge.ca
  version: ''
servers:
- url: https://admin.farmcommand.com/
security:
- FarmCommand Token: []
tags:
- name: recengine
paths:
  /recengine/token-login/:
    parameters: []
    post:
      operationId: recengine_token-login_create
      description: Token login for RecEngine users, returns token if logged in successfully
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                required:
                - password
                - username
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
      tags:
      - recengine
      requestBody:
        content:
          application/json:
            schema:
              required:
              - password
              - username
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
        required: true
      summary: Recengine token login create
      x-summary-source: derived
components:
  securitySchemes:
    FarmCommand_Token:
      type: apiKey
      name: token
      in: query
