openapi: 3.2.0
info:
  title: FarmCommand Integrations API
  termsOfService: https://www.farmcommand.com/terms-of-service
  contact:
    name: Product Support
    email: productsupport@farmersedge.ca
  version: ''
servers:
- url: https://admin.farmcommand.com/
security:
- FarmCommand Token: []
tags:
- name: Integrations
paths:
  /integrations/leaf/alerts/:
    parameters: []
    post:
      operationId: integrations_leaf_alerts_create
      description: 'Process Leaf Alerts; Used as a hook directly by LEAF.

        It accepts a flexible body that will be forwarded to PubSub,

        so long as the request is signed properly.'
      responses:
        '200':
          description: Leaf alert processed successfully.
        '400':
          description: Bad Request
      tags:
      - Integrations
      summary: Integrations leaf alerts create
      x-summary-source: derived
components:
  securitySchemes:
    FarmCommand_Token:
      type: apiKey
      name: token
      in: query
