swagger: '2.0'
info:
  title: FarmCommand canplug token-login API
  termsOfService: https://www.farmcommand.com/terms-of-service
  contact:
    name: Product Support
    email: productsupport@farmersedge.ca
  version: "1.0"
host: admin.farmcommand.com
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
security:
- FarmCommand Token: []
tags:
- name: token-login
paths:
  /token-login/:
    parameters: []
    post:
      operationId: token-login_create
      description: Token login for FarmCommand users, returns token if logged in successfully
      parameters:
      - name: data
        in: body
        required: true
        schema:
          required:
          - password
          - username
          type: object
          properties:
            username:
              type: string
            password:
              type: string
      responses:
        '201':
          description: ''
          schema:
            required:
            - password
            - username
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      tags:
      - token-login
securityDefinitions:
  FarmCommand Token:
    type: apiKey
    name: token
    in: query
